GPU: [0]

VERBOSE: True

OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 250
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
  TRAIN_DIR: '../dataset/train'
  VAL_DIR: '../dataset/val'
  SAVE_MODEL_DIR: '../model'
